name: node-ci

on:
  push:
    branches:
      - '**'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      
  build:
    runs-on: ubuntu-latest
    needs: lint  # Ensure build runs only if lint succeeds
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
